import java.io.File;
import java.io.FileWriter;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Scanner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;



public class sep_dblp_needed{

    private static HashMap<String,Integer> areaId;

    private static void init(){
        areaId.put("journals/tocs", 0);
        areaId.put("journals/tos", 0);
        areaId.put("journals/tcad", 0);
        areaId.put("journals/tc", 0);
        areaId.put("journals/tpds", 0);
        areaId.put("journals/taco", 0);
        areaId.put("journals/taas", 0);
        areaId.put("journals/todaes", 0);
        areaId.put("journals/tecs", 0);
        areaId.put("journals/trets", 0);
        areaId.put("journals/tvlsi", 0);
        areaId.put("journals/jpdc", 0);
        areaId.put("journals/jsa", 0);
        areaId.put("conf/parco", 0);
        areaId.put("journals/jetc", 0);
        areaId.put("journals/concurrency", 0);
        areaId.put("journals/dc", 0);
        areaId.put("journals/fgcs", 0);
        areaId.put("journals/integration", 0);
        areaId.put("journals/mam", 0);
        areaId.put("journals/rts", 0);
        areaId.put("journals/tjs", 0);
        areaId.put("conf/ppopp", 0);
        areaId.put("conf/fast", 0);
        areaId.put("conf/hpca", 0);
        areaId.put("conf/sc", 0);
        areaId.put("conf/asplos", 0);
        areaId.put("conf/isca", 0);
        areaId.put("conf/usenix", 0);
        areaId.put("conf/cloud", 0);
        areaId.put("conf/spaa", 0);
        areaId.put("conf/podc", 0);
        areaId.put("conf/fpga", 0);
        areaId.put("conf/cgo", 0);
        areaId.put("conf/date", 0);
        areaId.put("conf/eurosys", 0);
        areaId.put("conf/iccd", 0);
        areaId.put("conf/iccad", 0);
        areaId.put("conf/icdcs", 0);
        areaId.put("conf/codes", 0);
        areaId.put("conf/hipeac", 0);
        areaId.put("conf/sigmetrics", 0);
        areaId.put("conf/IEEEpact", 0);
        areaId.put("conf/icpp", 0);
        areaId.put("conf/ics", 0);
        areaId.put("conf/vee", 0);
        areaId.put("conf/ipps", 0);
        areaId.put("conf/performance", 0);
        areaId.put("conf/hpdc", 0);
        areaId.put("conf/itc", 0);
        areaId.put("conf/lisa", 0);
        areaId.put("conf/mss", 0);
        areaId.put("conf/rtas", 0);
        areaId.put("conf/cf", 0);
        areaId.put("conf/systor", 0);
        areaId.put("conf/nocs", 0);
        areaId.put("conf/asap", 0);
        areaId.put("conf/aspdac", 0);
        areaId.put("conf/europar", 0);
        areaId.put("conf/ets", 0);
        areaId.put("conf/fpl", 0);
        areaId.put("conf/fccm", 0);
        areaId.put("conf/glvlsi", 0);
        areaId.put("conf/ats", 0);
        areaId.put("conf/hpcc", 0);
        areaId.put("conf/hipc", 0);
        areaId.put("conf/mascots", 0);
        areaId.put("conf/ispa", 0);
        areaId.put("conf/ccgrid", 0);
        areaId.put("conf/npc", 0);
        areaId.put("conf/ica3pp", 0);
        areaId.put("conf/cases", 0);
        areaId.put("conf/fpt", 0);
        areaId.put("conf/icpads", 0);
        areaId.put("conf/iscas", 0);
        areaId.put("conf/islped", 0);
        areaId.put("conf/ispd", 0);
        areaId.put("conf/hoti", 0);
        areaId.put("conf/vts", 0);

        areaId.put("journals/jsac", 1);
        areaId.put("journals/tmc", 1);
        areaId.put("journals/ton", 1);
        areaId.put("journals/toit", 1);
        areaId.put("journals/tomccap", 1);
        areaId.put("journals/tosn", 1);
        areaId.put("journals/cn", 1);
        areaId.put("journals/tcom", 1);
        areaId.put("journals/twc", 1);
        areaId.put("journals/adhoc", 1);
        areaId.put("journals/comcom", 1);
        areaId.put("journals/tnsm", 1);
        areaId.put("journals/iet-com", 1);
        areaId.put("journals/jnca", 1);
        areaId.put("journals/monet", 1);
        areaId.put("journals/networks", 1);
        areaId.put("journals/ppna", 1);
        areaId.put("journals/wicomm", 1);
        areaId.put("journals/winet", 1);
        areaId.put("conf/sigcomm", 1);
        areaId.put("conf/mobicom", 1);
        areaId.put("conf/infocom", 1);
        areaId.put("conf/nsdi", 1);
        areaId.put("conf/sensys", 1);
        areaId.put("conf/conext", 1);
        areaId.put("conf/secon", 1);
        areaId.put("conf/ipsn", 1);
        areaId.put("conf/mobisys", 1);
        areaId.put("conf/icnp", 1);
        areaId.put("conf/mobihoc", 1);
        areaId.put("conf/nossdav", 1);
        areaId.put("conf/iwqos", 1);
        areaId.put("conf/imc", 1);
        areaId.put("conf/ancs", 1);
        areaId.put("conf/apnoms", 1);
        areaId.put("conf/forte", 1);
        areaId.put("conf/lcn", 1);
        areaId.put("conf/globecom", 1);
        areaId.put("conf/icc", 1);
        areaId.put("conf/icccn", 1);
        areaId.put("conf/mass", 1);
        areaId.put("conf/p2p", 1);
        areaId.put("conf/ipccc", 1);
        areaId.put("conf/wowmom", 1);
        areaId.put("conf/iscc", 1);
        areaId.put("conf/wcnc", 1);
        areaId.put("conf/networking", 1);
        areaId.put("conf/im", 1);
        areaId.put("conf/mswim", 1);
        areaId.put("conf/wasa", 1);
        areaId.put("conf/hotnets", 1);

        areaId.put("journals/tdsc", 2);
        areaId.put("journals/tifs", 2);
        areaId.put("journals/joc", 2);
        areaId.put("journals/compsec", 2);
        areaId.put("journals/dcc", 2);
        areaId.put("journals/jcs", 2);
        areaId.put("journals/ejisec", 2);
        areaId.put("journals/iet-ifs", 2);
        areaId.put("journals/imcs", 2);
        areaId.put("journals/ijics", 2);
        areaId.put("journals/ijisp", 2);
        areaId.put("journals/scn", 2);
        areaId.put("conf/ccs", 2);
        areaId.put("conf/eurocrypt", 2);
        areaId.put("conf/sp", 2);
        areaId.put("conf/crypto", 2);
        areaId.put("conf/uss", 2);
        areaId.put("conf/acsac", 2);
        areaId.put("conf/asiacrypt", 2);
        areaId.put("conf/esorics", 2);
        areaId.put("conf/fse", 2);
        areaId.put("conf/csfw", 2);
        areaId.put("conf/srds", 2);
        areaId.put("conf/ches", 2);
        areaId.put("conf/dsn", 2);
        areaId.put("conf/raid", 2);
        areaId.put("conf/pkc", 2);
        areaId.put("conf/ndss", 2);
        areaId.put("conf/tcc", 2);
        areaId.put("conf/wisec", 2);
        areaId.put("conf/sacmat", 2);
        areaId.put("conf/drm", 2);
        areaId.put("conf/ih", 2);
        areaId.put("conf/acns", 2);
        areaId.put("conf/ccs", 2);
        areaId.put("conf/acisp", 2);
        areaId.put("conf/ctrsa", 2);
        areaId.put("conf/dimva", 2);
        areaId.put("conf/dfrws", 2);
        areaId.put("conf/fc", 2);
        areaId.put("conf/trustcom", 2);
        areaId.put("conf/sec", 2);
        areaId.put("conf/isw", 2);
        areaId.put("conf/icdf2c", 2);
        areaId.put("conf/icics", 2);
        areaId.put("conf/securecomm", 2);
        areaId.put("conf/nspw", 2);
        areaId.put("conf/pam", 2);
        areaId.put("conf/pet", 2);
        areaId.put("conf/sacrypt", 2);
        areaId.put("conf/soups", 2);

        areaId.put("journals/toplas", 3);
        areaId.put("journals/tosem", 3);
        areaId.put("journals/tse", 3);
        areaId.put("journals/ase", 3);
        areaId.put("journals/ese", 3);
        areaId.put("journals/tsc", 3);
        areaId.put("journals/infsof", 3);
        areaId.put("journals/jfp", 3);
        areaId.put("journals/smr", 3);
        areaId.put("journals/jss", 3);
        areaId.put("journals/re", 3);
        areaId.put("journals/scp", 3);
        areaId.put("journals/sosym", 3);
        areaId.put("journals/stvr", 3);
        areaId.put("journals/spe", 3);
        areaId.put("journals/cl", 3);
        areaId.put("journals/ijseke", 3);
        areaId.put("journals/sttt", 3);
        areaId.put("journals/jlp", 3);
        areaId.put("journals/jwe", 3);
        areaId.put("journals/soca", 3);
        areaId.put("journals/sqj", 3);
        areaId.put("journals/tplp", 3);
        areaId.put("conf/pldi", 3);
        areaId.put("conf/popl", 3);
        areaId.put("conf/sigsoft", 3);
        areaId.put("conf/sosp", 3);
        areaId.put("conf/oopsla", 3);
        areaId.put("conf/kbse", 3);
        areaId.put("conf/icse", 3);
        areaId.put("conf/issta", 3);
        areaId.put("conf/osdi", 3);
        areaId.put("conf/ecoop", 3);
        areaId.put("conf/etaps", 3);
        areaId.put("conf/iwpc", 3);
        areaId.put("conf/re", 3);
        areaId.put("conf/caise", 3);
        areaId.put("conf/icfp", 3);
        areaId.put("conf/lctrts", 3);
        areaId.put("conf/models", 3);
        areaId.put("conf/cp", 3);
        areaId.put("conf/icsoc", 3);
        areaId.put("conf/wcre", 3);
        areaId.put("conf/icsm", 3);
        areaId.put("conf/vmcai", 3);
        areaId.put("conf/icws", 3);
        areaId.put("conf/middleware", 3);
        areaId.put("conf/sas", 3);
        areaId.put("conf/esem", 3);
        areaId.put("conf/fm", 3);
        areaId.put("conf/issre", 3);
        areaId.put("conf/hotos", 3);
        areaId.put("conf/pepm", 3);
        areaId.put("conf/paste", 3);
        areaId.put("conf/aplas", 3);
        areaId.put("conf/apsec", 3);
        areaId.put("conf/ease", 3);
        areaId.put("conf/iceccs", 3);
        areaId.put("conf/icst", 3);
        areaId.put("conf/ispass", 3);
        areaId.put("conf/scam", 3);
        areaId.put("conf/compsac", 3);
        areaId.put("conf/icfem", 3);
        areaId.put("conf/tools", 3);
        areaId.put("conf/IEEEscc", 3);
        areaId.put("conf/ispw", 3);
        areaId.put("conf/seke", 3);
        areaId.put("conf/icsr", 3);
        areaId.put("conf/icwe", 3);
        areaId.put("conf/spin", 3);
        areaId.put("conf/atva", 3);
        areaId.put("conf/lopstr", 3);
        areaId.put("conf/tase", 3);
        areaId.put("conf/msr", 3);
        areaId.put("conf/refsq", 3);
        areaId.put("conf/wicsa", 3);

        areaId.put("journals/tods", 4);
        areaId.put("journals/tois", 4);
        areaId.put("journals/tkde", 4);
        areaId.put("journals/vldb", 4);
        areaId.put("journals/tkdd", 4);
        areaId.put("journals/tweb", 4);
        areaId.put("journals/aei", 4);
        areaId.put("journals/dke", 4);
        areaId.put("journals/datamine", 4);
        areaId.put("journals/ejis", 4);
        areaId.put("journals/geoinformatica", 4);
        areaId.put("journals/ipm", 4);
        areaId.put("journals/isci", 4);
        areaId.put("journals/is", 4);
        areaId.put("journals/jasis", 4);
        areaId.put("journals/ws", 4);
        areaId.put("journals/kais", 4);
        areaId.put("journals/dpd", 4);
        areaId.put("journals/iam", 4);
        areaId.put("journals/ipl", 4);
        areaId.put("journals/ir", 4);
        areaId.put("journals/ijcis", 4);
        areaId.put("journals/gis", 4);
        areaId.put("journals/ijis", 4);
        areaId.put("journals/ijkm", 4);
        areaId.put("journals/ijswis", 4);
        areaId.put("journals/jcis", 4);
        areaId.put("journals/jdm", 4);
        areaId.put("journals/jiis", 4);
        areaId.put("journals/jsis", 4);
        areaId.put("conf/sigmod", 4);
        areaId.put("conf/kdd", 4);
        areaId.put("conf/icde", 4);
        areaId.put("conf/sigir", 4);
        areaId.put("conf/vldb", 4);
        areaId.put("conf/cikm", 4);
        areaId.put("conf/wsdm", 4);
        areaId.put("conf/pods", 4);
        areaId.put("conf/dasfaa", 4);
        areaId.put("conf/ecml", 4);
        areaId.put("conf/pkdd", 4);
        areaId.put("conf/semweb", 4);
        areaId.put("conf/icdm", 4);
        areaId.put("conf/icdt", 4);
        areaId.put("conf/edbt", 4);
        areaId.put("conf/cidr", 4);
        areaId.put("conf/sdm", 4);
        areaId.put("conf/apweb", 4);
        areaId.put("conf/dexa", 4);
        areaId.put("conf/ecir", 4);
        areaId.put("conf/esws", 4);
        areaId.put("conf/webdb", 4);
        areaId.put("conf/er", 4);
        areaId.put("conf/mdm", 4);
        areaId.put("conf/ssdbm", 4);
        areaId.put("conf/waim", 4);
        areaId.put("conf/ssd", 4);
        areaId.put("conf/pakdd", 4);
        areaId.put("conf/wise", 4);

        areaId.put("journals/tit", 5);
        areaId.put("journals/iandc", 5);
        areaId.put("journals/siamcomp", 5);
        areaId.put("journals/talg", 5);
        areaId.put("journals/tocl", 5);
        areaId.put("journals/toms", 5);
        areaId.put("journals/algorithmica", 5);
        areaId.put("journals/cc", 5);
        areaId.put("journals/fac", 5);
        areaId.put("journals/fmsd", 5);
        areaId.put("journals/informs", 5);
        areaId.put("journals/jcss", 5);
        areaId.put("journals/jgo", 5);
        areaId.put("journals/jsc", 5);
        areaId.put("journals/mscs", 5);
        areaId.put("journals/tcs", 5);
        areaId.put("journals/acta", 5);
        areaId.put("journals/apal", 5);
        areaId.put("journals/dam", 5);
        areaId.put("journals/fuin", 5);
        areaId.put("journals/lisp", 5);
        areaId.put("journals/ipl", 5);
        areaId.put("journals/jc", 5);
        areaId.put("journals/logcom", 5);
        areaId.put("journals/jsyml", 5);
        areaId.put("journals/lmcs", 5);
        areaId.put("journals/siamdm", 5);
        areaId.put("journals/mst", 5);
        areaId.put("conf/stoc", 5);
        areaId.put("conf/soda", 5);
        areaId.put("conf/cav", 5);
        areaId.put("conf/focs", 5);
        areaId.put("conf/lics", 5);
        areaId.put("conf/compgeom", 5);
        areaId.put("conf/esa", 5);
        areaId.put("conf/coco", 5);
        areaId.put("conf/icalp", 5);
        areaId.put("conf/cade", 5);
        areaId.put("conf/concur", 5);
        areaId.put("conf/hybrid", 5);
        areaId.put("conf/sat", 5);
        areaId.put("conf/csl", 5);
        areaId.put("conf/fmcad", 5);
        areaId.put("conf/fsttcs", 5);
        areaId.put("conf/ictac", 5);
        areaId.put("conf/ipco", 5);
        areaId.put("conf/rta", 5);
        areaId.put("conf/isaac", 5);
        areaId.put("conf/mfcs", 5);
        areaId.put("conf/stacs", 5);

        areaId.put("journals/tog", 6);
        areaId.put("journals/tip", 6);
        areaId.put("journals/tvcg", 6);
        areaId.put("journals/tomccap", 6);
        areaId.put("journals/cagd", 6);
        areaId.put("journals/cgf", 6);
        areaId.put("journals/cad", 6);
        areaId.put("journals/cvgip", 6);
        areaId.put("journals/tcsv", 6);
        areaId.put("journals/tmm", 6);
        areaId.put("journals/siamis", 6);
        areaId.put("journals/speech", 6);
        areaId.put("journals/comgeo", 6);
        areaId.put("journals/cg", 6);
        areaId.put("journals/dcg", 6);
        areaId.put("journals/spl", 6);
        areaId.put("journals/iet-ipr", 6);
        areaId.put("journals/jvcir", 6);
        areaId.put("journals/mms", 6);
        areaId.put("journals/mta", 6);
        areaId.put("journals/sigpro", 6);
        areaId.put("journals/spic", 6);
        areaId.put("journals/vc", 6);
        areaId.put("conf/mm", 6);
        areaId.put("conf/siggraph", 6);
        areaId.put("conf/vr", 6);
        areaId.put("conf/visualization", 6);
        areaId.put("conf/mir", 6);
        areaId.put("conf/si3d", 6);
        areaId.put("conf/sca", 6);
        areaId.put("conf/dcc", 6);
        areaId.put("conf/eurographics", 6);
        areaId.put("conf/vissym", 6);
        areaId.put("conf/sgp", 6);
        areaId.put("conf/rt", 6);
        areaId.put("conf/icassp", 6);
        areaId.put("conf/icmcs", 6);
        areaId.put("conf/ismar", 6);
        areaId.put("conf/pg", 6);
        areaId.put("conf/sma", 6);
        areaId.put("conf/vrst", 6);
        areaId.put("conf/ca", 6);
        areaId.put("conf/cgi", 6);
        areaId.put("conf/interspeech", 6);
        areaId.put("conf/gmp", 6);
        areaId.put("conf/apvis", 6);
        areaId.put("conf/icip", 6);
        areaId.put("conf/mmm", 6);
        areaId.put("conf/pcm", 6);
        areaId.put("conf/smi", 6);

        areaId.put("journals/ai", 7);
        areaId.put("journals/pami", 7);
        areaId.put("journals/ijcv", 7);
        areaId.put("journals/jmlr", 7);
        areaId.put("journals/tap", 7);
        areaId.put("journals/tslp", 7);
        areaId.put("journals/aamas", 7);
        areaId.put("journals/coling", 7);
        areaId.put("journals/cviu", 7);
        areaId.put("journals/dke", 7);
        areaId.put("journals/ec", 7);
        areaId.put("journals/taffco", 7);
        areaId.put("journals/taslp", 7);
        areaId.put("journals/tcyb", 7);
        areaId.put("journals/tec", 7);
        areaId.put("journals/tfs", 7);
        areaId.put("journals/tnn", 7);
        areaId.put("journals/ijar", 7);
        areaId.put("journals/jair", 7);
        areaId.put("journals/jar", 7);
        areaId.put("journals/ml", 7);
        areaId.put("journals/neco", 7);
        areaId.put("journals/nn", 7);
        areaId.put("conf/par", 7);
        areaId.put("journals/talip", 7);
        areaId.put("journals/apin", 7);
        areaId.put("journals/artmed", 7);
        areaId.put("journals/alife", 7);
        areaId.put("journals/ci", 7);
        areaId.put("journals/csl", 7);
        areaId.put("journals/connection", 7);
        areaId.put("journals/dss", 7);
        areaId.put("journals/eaai", 7);
        areaId.put("journals/es", 7);
        areaId.put("journals/eswa", 7);
        areaId.put("journals/fss", 7);
        areaId.put("journals/tciaig", 7);
        areaId.put("journals/ivc", 7);
        areaId.put("journals/ida", 7);
        areaId.put("journals/ijcia", 7);
        areaId.put("journals/ijis", 7);
        areaId.put("journals/ijns", 7);
        areaId.put("journals/ijprai", 7);
        areaId.put("journals/ijdar", 7);
        areaId.put("journals/jetai", 7);
        areaId.put("journals/kbs", 7);
        areaId.put("journals/mt", 7);
        areaId.put("journals/mva", 7);
        areaId.put("journals/nc", 7);
        areaId.put("journals/nle", 7);
        areaId.put("journals/nca", 7);
        areaId.put("journals/npl", 7);
        areaId.put("journals/ijon", 7);
        areaId.put("journals/paa", 7);
        areaId.put("journals/prl", 7);
        areaId.put("journals/soco", 7);
        areaId.put("journals/wias", 7);
        areaId.put("conf/aaai", 7);
        areaId.put("conf/nips", 7);
        areaId.put("conf/acl", 7);
        areaId.put("conf/cvpr", 7);
        areaId.put("conf/iccv", 7);
        areaId.put("conf/icml", 7);
        areaId.put("conf/ijcai", 7);
        areaId.put("conf/colt", 7);
        areaId.put("conf/emnlp", 7);
        areaId.put("conf/ecai", 7);
        areaId.put("conf/eccv", 7);
        areaId.put("conf/icra", 7);
        areaId.put("conf/aips", 7);
        areaId.put("conf/iccbr", 7);
        areaId.put("conf/coling", 7);
        areaId.put("conf/kr", 7);
        areaId.put("conf/uai", 7);
        areaId.put("conf/atal", 7);
        areaId.put("conf/ppsn", 7);
        areaId.put("conf/aistats", 7);
        areaId.put("conf/accv", 7);
        areaId.put("conf/acml", 7);
        areaId.put("conf/bmvc", 7);
        areaId.put("conf/conll", 7);
        areaId.put("conf/gecco", 7);
        areaId.put("conf/ictai", 7);
        areaId.put("conf/iros", 7);
        areaId.put("conf/alt", 7);
        areaId.put("conf/icann", 7);
        areaId.put("conf/fgr", 7);
        areaId.put("conf/icdar", 7);
        areaId.put("conf/ilp", 7);
        areaId.put("conf/ksem", 7);
        areaId.put("conf/iconip", 7);
        areaId.put("conf/icpr", 7);
        areaId.put("conf/icb", 7);
        areaId.put("conf/ijcnn", 7);
        areaId.put("conf/pricai", 7);
        areaId.put("conf/naacl", 7);

        areaId.put("journals/tochi", 8);
        areaId.put("journals/ijmms", 8);
        areaId.put("journals/cscw", 8);
        areaId.put("journals/hhci", 8);
        areaId.put("journals/thms", 8);
        areaId.put("journals/iwc", 8);
        areaId.put("journals/ijhci", 8);
        areaId.put("journals/umuai", 8);
        areaId.put("journals/behaviourIT", 8);
        areaId.put("journals/puc", 8);
        areaId.put("journals/percom", 8);
        areaId.put("conf/cscw", 8);
        areaId.put("conf/chi", 8);
        areaId.put("conf/huc", 8);
        areaId.put("conf/group", 8);
        areaId.put("conf/iui", 8);
        areaId.put("conf/tabletop", 8);
        areaId.put("conf/uist", 8);
        areaId.put("conf/ecscw", 8);
        areaId.put("conf/percom", 8);
        areaId.put("conf/mhci", 8);
        areaId.put("conf/ACMdis", 8);
        areaId.put("conf/icmi", 8);
        areaId.put("conf/assets", 8);
        areaId.put("conf/graphicsinterface", 8);
        areaId.put("conf/uic", 8);
        areaId.put("conf/haptics", 8);
        areaId.put("conf/interact", 8);
        areaId.put("conf/acmidc", 8);
        areaId.put("conf/cscwd", 8);
        areaId.put("conf/coopis", 8);
        areaId.put("conf/mobiquitous", 8);
        areaId.put("conf/avi", 8);
    }
    public static void main(String[] args) throws Exception{
        areaId=new HashMap<>();
        init();

        Scanner fin=new Scanner(new File("dblp_needed.csv"));
        HashMap<String,HashMap<Integer,Integer>> authorArea=new HashMap<>();
        HashMap<String,Integer> nameMp=new HashMap<>();
        HashMap<String,Integer> author_first_year=new HashMap<>();
        /**
         * 
         */
        int nameIndex=0;

        StringBuilder tempgraphsb=new StringBuilder();
        while(fin.hasNextLine()){
            String[] segs=fin.nextLine().split(",");
            if(segs.length<=2) continue;
            String confname=segs[0];
            int confId=areaId.get(confname);
            String year=segs[1];
            for(int i=2;i<segs.length;++i){
                String name=segs[i];
                if(nameMp.containsKey(name)==false) nameMp.put(name, nameIndex++);

                if(authorArea.containsKey(name)==false) authorArea.put(name, new HashMap<>());
                if(authorArea.get(name).containsKey(confId)==false) authorArea.get(name).put(confId, 0);
                int cnt=authorArea.get(name).get(confId);
                authorArea.get(name).put(confId, cnt+1);

                //
                if(author_first_year.containsKey(name)==false) author_first_year.put(name,3000);

                if(author_first_year.get(name)>Integer.parseInt(year)) author_first_year.put(name,Integer.parseInt(year));

            }
            if(segs.length==3) continue;
            for(int i=2;i<segs.length-1;++i){
                for(int j=i+1;j<segs.length;++j){
                    String name1=segs[i];
                    String name2=segs[j];
                    tempgraphsb.append(Integer.toString(nameMp.get(name1))+","+Integer.toString(nameMp.get(name2))+","+year+"\n");
                }
            }
        }
        //temp
        // FileWriter tempgraphfw=new FileWriter("temp_graph.csv");
        // tempgraphfw.write(tempgraphsb.toString());
        // tempgraphfw.close();

        //test
        ArrayList<Double> temp=new ArrayList<>();

        StringBuilder authorsb=new StringBuilder();
        Iterator<String> it=authorArea.keySet().iterator();
        while(it.hasNext()){
            String name=it.next();
            HashMap<Integer,Integer> areacnt=authorArea.get(name);
            int[] areanum=new int[10];
            int realarea=0,big=0;
            int totalpaper=0;
            for(int i=0;i<9;++i){
                areanum[i]=0;
                if(areacnt.containsKey(i)) areanum[i]=areacnt.get(i);
                if(big<areanum[i]){
                    big=areanum[i];
                    realarea=i;
                }
                totalpaper+=areanum[i];
            }
            String totallevel="";
            int dualYear=2022-author_first_year.get(name);
            if(dualYear<=0) dualYear=1;
            double paperPerYear=(double)totalpaper/dualYear;

            temp.add(paperPerYear);

            if(paperPerYear<=1) totallevel="Poor";
            else if(paperPerYear>1&&paperPerYear<=3) totallevel="Fair";
            else if(paperPerYear>3&&paperPerYear<=8) totallevel="Good";
            else if(paperPerYear>8) totallevel="Excellent";

            // if(totalpaper<=5) totallevel="Poor";
            // else if(totalpaper>=6&&totalpaper<=20) totallevel="Fair";
            // else if(totalpaper>=21&&totalpaper<=50) totallevel="Good";
            // else if(totalpaper>50) totallevel="Excellent";
            String areastr="";
            if(realarea==0) areastr="CA";
            else if(realarea==1) areastr="CN";
            else if(realarea==2) areastr="NS";
            else if(realarea==3) areastr="SE";
            else if(realarea==4) areastr="DB";
            else if(realarea==5) areastr="TH";
            else if(realarea==6) areastr="CG";
            else if(realarea==7) areastr="AI";
            else if(realarea==8) areastr="HI";
            authorsb.append(Integer.toString(nameMp.get(name))+","+name+","+areastr+","+totallevel+"\n");

        }

        // //temp
        // FileWriter authorfw=new FileWriter("author_info.csv");
        // authorfw.write(authorsb.toString());
        // authorfw.close();

        Collections.sort(temp);
        for(int i=0;i<temp.size();i+=5000){
            System.out.print(temp.get(i));
            System.out.print(" ");
        }

        fin.close();
    }
}